---
# tasks file for calculator
# TODO tady
- name: Ensure temp directory exists on control node
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: "directory"
  changed_when: False

- name: Ensure temp directory exists on target node
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: "directory"

- name: Download Calculator Binary from Gitlab to control node
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ calculator_download_url }}"
    dest: "{{ tmp_dir }}"
    headers: "{{ gitlab_auth_headers | items2dict }}"

- name: Download Calculator Templates from Gitlab to control node
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ template_download_url }}"
    dest: "{{ tmp_dir }}"
    headers: "{{ gitlab_auth_headers | items2dict }}"


- name: Create base dir for calculator
  become: true
  ansible.builtin.file:
    path: "{{ calculator_base_dir }}"
    mode: "0775"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
    state: "directory"
  notify: Restart Calculator Service

- name: Ensure log directory exists on target node
  become: true
  ansible.builtin.file:
    path: "{{ calculator_log_dir }}"
    mode: "0775"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
    state: "directory"  
  notify: Restart Calculator Service  
  changed_when: False

- name: Upload Calculator Binary to host
  become: true
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ calculator_binary_filename }}"
    dest: "{{ calculator_base_dir }}"
    mode: "0750"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
  notify: Restart Calculator Service

- name: Upload templates (and unpack)
  ansible.builtin.unarchive:
    src: "{{ tmp_dir }}/{{ templates_archive_filename }}"
    dest: "{{ tmp_dir }}"
    remote_src: no
    

- name: Move templates from their archived subdir
  become: true
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/calculator-web/templates"
    dest: "{{ calculator_base_dir }}"
    remote_src: yes
    mode: "0775"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
  notify: Restart Calculator Service


- name: Configure systemd service
  ansible.builtin.import_tasks:
    file: "service.yml"