- name: Check and install java 17 on target node
  become: true
  run_once: true
  apt:
    name: openjdk-17-jdk
    state: present

- name: Copy systemd service unit file
  copy:
    src: roles/bike_sharing/files/{{authenticator_service_name}}
    dest: /etc/systemd/system/{{authenticator_service_name}}
    owner: nodeadm
    group: nodeadm
    mode: '0644'
  become: true
  notify: Restart auth service

- name: Start and enable the auth service
  systemd:
    name: "{{authenticator_service_name}}"
    state: started
    enabled: 'yes'
  become: true
