- name: Check and install java 17 on target node
  become: true
  run_once: true
  apt:
    name: openjdk-17-jdk
    state: present

- name: Configure auth application service
  ansible.builtin.import_tasks:
    file: "auth_service.yml"

- name: Configure bike location service
  ansible.builtin.import_tasks:
    file: "location_service.yml"

- name: Configure bike sharing service
  ansible.builtin.import_tasks:
    file: "bike_service.yml"

- name: Configure react client serivce
  ansible.builtin.import_tasks:
    file: "react_service.yml"
