---
- name: Check and install java 17 on target node
  become: true
  run_once: true
  apt:
        name: openjdk-17-jdk
        state: present
- name: Start auth service
  command: "nohup java -jar {{bike_sharing_base_dir}}/{{authenticator_service_executable}} &"
  async: 5  # Adjust this according to your service's startup time
  poll: 0
  register: java_service
