---
- name: unzip archive
  ansible.builtin.unarchive:
    src: "{{client_root_dir}}/{{client_archive_name}}"
    dest: "{{client_root_dir}}"
    remote_src: yes
    extra_opts: [--overwrite]
  become: true

- name: Ensure the directory for nginx configuration exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory


- name: copy configuration to nginx server
  ansible.builtin.copy:
    src: "{{client_root_dir}}/nginx.conf"
    dest: "/etc/nginx/conf.d/default.conf"
    remote_src: yes 
  become: true


- name: copy build to nginx html
  ansible.builtin.shell:
      cmd: "cp -r {{client_root_dir}}/build/* /usr/share/nginx/html/"
  become: true



- name: Start Nginx service
  service:
    name: nginx
    state: started
  become: true