---
- name: Configure init script
  become: true
  ansible.builtin.template:
    src: templates/calculator.sh.j2
    dest: "{{ calculator_script }}"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
    mode: 0554
  notify: Restart Calculator Service

- name: Configure systemd unit
  become: true
  ansible.builtin.template:
    src: templates/calculator.service.j2
    dest: "{{ systemd_dir }}/{{ calculator_service_name }}.service"
    owner: "{{ calculator_user }}"
    group: "{{ calculator_group }}"
    mode: 0554
  notify: Restart Calculator Service

- name: Ensure calculator service is started
  become: true
  ansible.builtin.service:
    name: "{{ calculator_service_name }}"
    daemon_reload: true
    state: started    