---
# tasks file for docker_bike_sharing

- name: Remove old dir
  ansible.builtin.shell: rm -rf BIKE_SHARING/

- name: Clone new version
  ansible.builtin.shell: git clone --branch hrabik https://github.com/Badjokke/BIKE_SHARING.git    

- name: Get host info
  community.docker.docker_host_info:
    containers: yes
    images: yes
  register: docker_info

- name: Remove all containers and their volumes
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
    keep_volumes: no
  loop: "{{ docker_info.containers | map(attribute='Id') }}"

- name: Remove all images
  community.docker.docker_image:
    name: "{{ item }}"
    state: absent
    force_absent: yes
  loop: "{{ docker_info.images | map(attribute='Id') }}"

- name: Docker compose up
  ansible.builtin.shell:  | 
    cd BIKE_SHARING/
    sudo docker compose up -d


    