---
# tasks file for docker_bike_sharing
- name: Clone of a single branch
  ansible.builtin.git:
    repo: https://github.com/Badjokke/BIKE_SHARING.git
    dest: /BIKE_SHARING
    single_branch: yes
    update: yes
    version: master

- name: Stop all services
  community.docker.docker_compose_v2:
    project_src: /BIKE_SHARING
    state: stopped

- name: Create and start services
  community.docker.docker_compose_v2:
      project_src: /BIKE_SHARING
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output