
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "trefil" ]
  pull_request:
    branches: [ "trefil" ]

env:
    CI: false

jobs:
  test:
    name: Test all apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Bike Sharing test
        run: |
          cd bike_sharing
          mvn test

      - name: Bike Sharing Auth test
        run: |
          cd bike_sharing_auth
          mvn test

      - name: Bike Sharing location test
        run: |
          cd bike_sharing_location
          mvn test

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Bike Sharing UI test
        run: |
          cd bike_sharing_ui
          npm ci
          npm test

  build:
    name: Build all apps
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Bike Sharing
        run: |
          cd bike_sharing
          mvn clean install

      - name: print Bike Sharing
        run: |
          cd bike_sharing 
          cd target
          ls

      - name: Save Artifact from Bike Sharing
        uses: actions/upload-artifact@v4
        with:
          name: bike_sharing
          path: bike_sharing/target/bike_sharing-0.0.1-SNAPSHOT.war

      - name: Build Bike Sharing Auth
        run: |
          cd bike_sharing_auth
          mvn clean install

      - name: print Bike Sharing Auth
        run: |
          cd bike_sharing_auth
          cd target
          ls

      - name: Save Artifact from Bike Sharing Auth
        uses: actions/upload-artifact@v4
        with:
          name: bike_sharing_auth
          path: bike_sharing_auth/target/authenticator-0.0.1-SNAPSHOT.war

      - name: Build Bike Sharing Location
        run: |
          cd bike_sharing_location
          mvn clean install

      - name: print Bike Sharing Location
        run: |
          cd bike_sharing_location
          cd target
          ls

      - name: Save Artifact from Bike Sharing Location
        uses: actions/upload-artifact@v4
        with:
          name: bike_sharing_location
          path: bike_sharing_location/target/bike_sharing_location-0.0.1-SNAPSHOT.war

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build Bike Sharing UI
        run: |
          cd bike_sharing_ui
          npm ci
          npm run build


      - name: Save Artifact from Bike Sharing UI
        uses: actions/upload-artifact@v4
        with:
          name: bike-sharing-ui
          path: bike_sharing_ui/build

      #- name: Copy artifacts for production run
      #  run: |
      #    cd bike_sharing_ui
      #    cp ./nginx.conf /etc/nginx/conf.d/default.conf
      #    cp -r /build/* /usr/share/nginx/html
          
  upload:
    name: Uploads all binaries to production server
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Create directory for artifacts
        run: |
          sudo mkdir -p /artifacts_github
      - name: Download bike_sharing artifact
        uses: actions/download-artifact@v4
        with:
          name: bike_sharing
          path: /artifacts_github
      #- name: Upload bike_sharing artifact to server
      #  run: |
      #    scp -r /artifacts_github/bike_sharing.war nodeadm@147.228.173.146:/home/nodeadm/artifact
      #  env:
      #      SSH_PRIVATE_KEY



#      - name: Save Artifact from Bike Sharing UI
#        uses: actions/upload-artifact@v4
#        with:
#          name: bike_sharing_ui
#          path: bike_sharing_ui/target/bike_sharing_location-0.0.1-SNAPSHOT.war

#      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
